In [1]:
import collections
import string

In [2]:
sentence = 'Baa, baa, black sheep, \
Have you any wool? \
Yes, sir, yes, sir, \
Three bags full; \
One for the master, \
And one for the dame, \
And one for the little boy \
Who lives down the lane.'

In [4]:
sentences = sentence.split()

In [5]:
sentences

['Baa,',
 'baa,',
 'black',
 'sheep,',
 'Have',
 'you',
 'any',
 'wool?',
 'Yes,',
 'sir,',
 'yes,',
 'sir,',
 'Three',
 'bags',
 'full;',
 'One',
 'for',
 'the',
 'master,',
 'And',
 'one',
 'for',
 'the',
 'dame,',
 'And',
 'one',
 'for',
 'the',
 'little',
 'boy',
 'Who',
 'lives',
 'down',
 'the',
 'lane.']

In [6]:
sentences = [sentence,\
             'Hickory, dickory, dock. The mouse ran up the clock. The clock struck one, The mouse ran down, Hickory, dickory, dock.']

In [9]:
wordList = [word for line in sentences for word in line.split()]

In [10]:
wordList

['Baa,',
 'baa,',
 'black',
 'sheep,',
 'Have',
 'you',
 'any',
 'wool?',
 'Yes,',
 'sir,',
 'yes,',
 'sir,',
 'Three',
 'bags',
 'full;',
 'One',
 'for',
 'the',
 'master,',
 'And',
 'one',
 'for',
 'the',
 'dame,',
 'And',
 'one',
 'for',
 'the',
 'little',
 'boy',
 'Who',
 'lives',
 'down',
 'the',
 'lane.',
 'Hickory,',
 'dickory,',
 'dock.',
 'The',
 'mouse',
 'ran',
 'up',
 'the',
 'clock.',
 'The',
 'clock',
 'struck',
 'one,',
 'The',
 'mouse',
 'ran',
 'down,',
 'Hickory,',
 'dickory,',
 'dock.']

In [11]:
collections.Counter(wordList)

Counter({'Baa,': 1,
         'baa,': 1,
         'black': 1,
         'sheep,': 1,
         'Have': 1,
         'you': 1,
         'any': 1,
         'wool?': 1,
         'Yes,': 1,
         'sir,': 2,
         'yes,': 1,
         'Three': 1,
         'bags': 1,
         'full;': 1,
         'One': 1,
         'for': 3,
         'the': 5,
         'master,': 1,
         'And': 2,
         'one': 2,
         'dame,': 1,
         'little': 1,
         'boy': 1,
         'Who': 1,
         'lives': 1,
         'down': 1,
         'lane.': 1,
         'Hickory,': 2,
         'dickory,': 2,
         'dock.': 2,
         'The': 3,
         'mouse': 2,
         'ran': 2,
         'up': 1,
         'clock.': 1,
         'clock': 1,
         'struck': 1,
         'one,': 1,
         'down,': 1})

In [12]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
_bow = sentence.lower().translate(str.maketrans('','',string.punctuation)).split()
_bow

['baa',
 'baa',
 'black',
 'sheep',
 'have',
 'you',
 'any',
 'wool',
 'yes',
 'sir',
 'yes',
 'sir',
 'three',
 'bags',
 'full',
 'one',
 'for',
 'the',
 'master',
 'and',
 'one',
 'for',
 'the',
 'dame',
 'and',
 'one',
 'for',
 'the',
 'little',
 'boy',
 'who',
 'lives',
 'down',
 'the',
 'lane']

In [14]:
collections.Counter(_bow)

Counter({'baa': 2,
         'black': 1,
         'sheep': 1,
         'have': 1,
         'you': 1,
         'any': 1,
         'wool': 1,
         'yes': 2,
         'sir': 2,
         'three': 1,
         'bags': 1,
         'full': 1,
         'one': 3,
         'for': 3,
         'the': 4,
         'master': 1,
         'and': 2,
         'dame': 1,
         'little': 1,
         'boy': 1,
         'who': 1,
         'lives': 1,
         'down': 1,
         'lane': 1})

In [15]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
count = CountVectorizer()

In [17]:
sentence

'Baa, baa, black sheep, Have you any wool? Yes, sir, yes, sir, Three bags full; One for the master, And one for the dame, And one for the little boy Who lives down the lane.'

In [24]:
bow = count.fit_transform(np.array([sentence]))

In [25]:
bow

<1x24 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [27]:
count.vocabulary_

{'baa': 2,
 'black': 4,
 'sheep': 16,
 'have': 10,
 'you': 23,
 'any': 1,
 'wool': 21,
 'yes': 22,
 'sir': 17,
 'three': 19,
 'bags': 3,
 'full': 9,
 'one': 15,
 'for': 8,
 'the': 18,
 'master': 14,
 'and': 0,
 'dame': 6,
 'little': 12,
 'boy': 5,
 'who': 20,
 'lives': 13,
 'down': 7,
 'lane': 11}

In [31]:
bow.toarray()

array([[2, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 2, 4, 1, 1, 1,
        2, 1]], dtype=int64)

In [32]:
counts = bow.toarray().ravel()
counts

array([2, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 2, 4, 1, 1, 1,
       2, 1], dtype=int64)

In [33]:
#Get the features
#your code goes here
features = count.get_feature_names()
features

['and',
 'any',
 'baa',
 'bags',
 'black',
 'boy',
 'dame',
 'down',
 'for',
 'full',
 'have',
 'lane',
 'little',
 'lives',
 'master',
 'one',
 'sheep',
 'sir',
 'the',
 'three',
 'who',
 'wool',
 'yes',
 'you']

In [34]:
#get the map words to their counts
dict(zip(features, counts))

{'and': 2,
 'any': 1,
 'baa': 2,
 'bags': 1,
 'black': 1,
 'boy': 1,
 'dame': 1,
 'down': 1,
 'for': 3,
 'full': 1,
 'have': 1,
 'lane': 1,
 'little': 1,
 'lives': 1,
 'master': 1,
 'one': 3,
 'sheep': 1,
 'sir': 2,
 'the': 4,
 'three': 1,
 'who': 1,
 'wool': 1,
 'yes': 2,
 'you': 1}

In [35]:
count = CountVectorizer(stop_words='english')

In [36]:
bow = count.fit_transform(np.array([sentence]))

In [37]:
count.vocabulary_

{'baa': 0,
 'black': 2,
 'sheep': 9,
 'wool': 11,
 'yes': 12,
 'sir': 10,
 'bags': 1,
 'master': 8,
 'dame': 4,
 'little': 6,
 'boy': 3,
 'lives': 7,
 'lane': 5}

In [39]:
bow.toarray()

array([[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2]], dtype=int64)

In [46]:
count = CountVectorizer(stop_words='english', ngram_range=(1,2))
bow = count.fit_transform(np.array([sentence]))
count.vocabulary_

{'baa': 0,
 'black': 5,
 'sheep': 18,
 'wool': 23,
 'yes': 25,
 'sir': 20,
 'bags': 3,
 'master': 16,
 'dame': 9,
 'little': 12,
 'boy': 7,
 'lives': 14,
 'lane': 11,
 'baa baa': 1,
 'baa black': 2,
 'black sheep': 6,
 'sheep wool': 19,
 'wool yes': 24,
 'yes sir': 26,
 'sir yes': 22,
 'sir bags': 21,
 'bags master': 4,
 'master dame': 17,
 'dame little': 10,
 'little boy': 13,
 'boy lives': 8,
 'lives lane': 15}

In [47]:
from sklearn.feature_extraction.text import TfidfTransformer

In [48]:
sentences = ['Singapore is a island city  south east asia ', \
             'Singapore has one main island with 62 other islands', \
            'Singapore has a tropical rainforest climate with no distinctive seasons. The currency of Singapore is the Singapore dollar.']

In [49]:
countv = CountVectorizer(stop_words='english')
tfidf = TfidfTransformer(use_idf=True,\
                        norm = 'l2', \
                        smooth_idf=True)

In [50]:
print(tfidf.fit_transform(countv.fit_transform(np.array(sentences))))

  (0, 14)	0.450504072643198
  (0, 13)	0.2660749625405929
  (0, 8)	0.3426199591918006
  (0, 7)	0.450504072643198
  (0, 2)	0.450504072643198
  (0, 1)	0.450504072643198
  (1, 13)	0.2980315863446099
  (1, 10)	0.5046113401371842
  (1, 9)	0.5046113401371842
  (1, 8)	0.3837699307603192
  (1, 0)	0.5046113401371842
  (2, 15)	0.31404571791576386
  (2, 13)	0.5564413800315426
  (2, 12)	0.31404571791576386
  (2, 11)	0.31404571791576386
  (2, 6)	0.31404571791576386
  (2, 5)	0.31404571791576386
  (2, 4)	0.31404571791576386
  (2, 3)	0.31404571791576386


In [51]:
countv.vocabulary_

{'singapore': 13,
 'island': 8,
 'city': 2,
 'south': 14,
 'east': 7,
 'asia': 1,
 'main': 10,
 '62': 0,
 'islands': 9,
 'tropical': 15,
 'rainforest': 11,
 'climate': 3,
 'distinctive': 5,
 'seasons': 12,
 'currency': 4,
 'dollar': 6}

In [52]:
countv = CountVectorizer(stop_words='english')
tfidf = TfidfTransformer(use_idf=False,\
                        norm = 'l2', \
                        smooth_idf=False)

In [53]:
_bow = countv.fit_transform(np.array(sentences))

In [54]:
tfi = tfidf.fit_transform(_bow)
print(tfi)

  (0, 1)	0.4082482904638631
  (0, 2)	0.4082482904638631
  (0, 7)	0.4082482904638631
  (0, 8)	0.4082482904638631
  (0, 13)	0.4082482904638631
  (0, 14)	0.4082482904638631
  (1, 0)	0.4472135954999579
  (1, 8)	0.4472135954999579
  (1, 9)	0.4472135954999579
  (1, 10)	0.4472135954999579
  (1, 13)	0.4472135954999579
  (2, 3)	0.25
  (2, 4)	0.25
  (2, 5)	0.25
  (2, 6)	0.25
  (2, 11)	0.25
  (2, 12)	0.25
  (2, 13)	0.75
  (2, 15)	0.25


In [55]:
countv = CountVectorizer(stop_words='english')
tfidf = TfidfTransformer(use_idf=False,\
                        norm = 'l1', \
                        smooth_idf=False)
_bow = countv.fit_transform(np.array(sentences))
tfi = tfidf.fit_transform(_bow)
print(tfi)

  (0, 1)	0.16666666666666666
  (0, 2)	0.16666666666666666
  (0, 7)	0.16666666666666666
  (0, 8)	0.16666666666666666
  (0, 13)	0.16666666666666666
  (0, 14)	0.16666666666666666
  (1, 0)	0.2
  (1, 8)	0.2
  (1, 9)	0.2
  (1, 10)	0.2
  (1, 13)	0.2
  (2, 3)	0.1
  (2, 4)	0.1
  (2, 5)	0.1
  (2, 6)	0.1
  (2, 11)	0.1
  (2, 12)	0.1
  (2, 13)	0.3
  (2, 15)	0.1
